version: "3.9"

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: phonebot
      POSTGRES_PASSWORD: phonebot
      POSTGRES_DB: phonebot
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    restart: unless-stopped
#    ports:
#      - "6379:6379"

  bot:
    build: .
    restart: unless-stopped
    depends_on:
      - db
      - redis
    env_file:
      - .env

volumes:
  pgdata:
